//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int IdConfiguration { get; set; }
        public string Nombre { get; set; }
        public string TagName { get; set; }
        public string Value { get; set; }
    }
}
