//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FriPriEntities : DbContext
    {
        public FriPriEntities()
            : base("name=FriPriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Configuration> Configuration { get; set; }
        public DbSet<Dimensions> Dimensions { get; set; }
        public DbSet<DimensionsCategories> DimensionsCategories { get; set; }
        public DbSet<DimensionsTypes> DimensionsTypes { get; set; }
        public DbSet<EventsLogs> EventsLogs { get; set; }
        public DbSet<Forms> Forms { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<ProductsForms> ProductsForms { get; set; }
        public DbSet<Profiles> Profiles { get; set; }
        public DbSet<ProfilesDimensions> ProfilesDimensions { get; set; }
        public DbSet<Publishers> Publishers { get; set; }
        public DbSet<Subscriptions> Subscriptions { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UsersDimensions> UsersDimensions { get; set; }
        public DbSet<Promos> Promos { get; set; }
    }
}
