//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dimensions
    {
        public Dimensions()
        {
            this.ProfilesDimensions = new HashSet<ProfilesDimensions>();
            this.UsersDimensions = new HashSet<UsersDimensions>();
        }
    
        public int IdDimension { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdDimensionType { get; set; }
        public Nullable<int> IdDimensionCategory { get; set; }
        public string Unit { get; set; }
        public Nullable<int> DurationHours { get; set; }
        public string LongDescription { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<bool> SwitchValue { get; set; }
        public Nullable<bool> Active { get; set; }
        public string TagName { get; set; }
    
        public virtual DimensionsCategories DimensionsCategories { get; set; }
        public virtual DimensionsTypes DimensionsTypes { get; set; }
        public virtual ICollection<ProfilesDimensions> ProfilesDimensions { get; set; }
        public virtual ICollection<UsersDimensions> UsersDimensions { get; set; }
    }
}
