//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimensionsTypes
    {
        public DimensionsTypes()
        {
            this.Dimensions = new HashSet<Dimensions>();
        }
    
        public int IdDimensionType { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public string TagName { get; set; }
    
        public virtual ICollection<Dimensions> Dimensions { get; set; }
    }
}
