//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forms
    {
        public Forms()
        {
            this.ProductsForms = new HashSet<ProductsForms>();
        }
    
        public int IdForm { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public string TagName { get; set; }
    
        public virtual ICollection<ProductsForms> ProductsForms { get; set; }
    }
}
