//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class NaranyaNotification
    {
        public int idNaranyaNotification { get; set; }
        public string id_event { get; set; }
        public string ipn_url { get; set; }
        public string ipn_type { get; set; }
        public string verify_sign { get; set; }
        public string id_app { get; set; }
        public string id_customer { get; set; }
        public string id_transaction { get; set; }
        public Nullable<int> amount { get; set; }
        public string currency { get; set; }
        public string id_subscription { get; set; }
        public string status { get; set; }
        public string id_service { get; set; }
        public Nullable<int> created { get; set; }
        public Nullable<int> updated { get; set; }
    }
}
