//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsForms
    {
        public int IdProductForm { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public Nullable<int> IdForm { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Token { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Footer { get; set; }
        public string SubscribeButtonText { get; set; }
        public string UrlLogo { get; set; }
        public string UrlBackground { get; set; }
        public string ColorSuperiorBar { get; set; }
        public string CssClassFeatured { get; set; }
        public string CssClassActual { get; set; }
        public string TitleColor { get; set; }
    
        public virtual Forms Forms { get; set; }
        public virtual Products Products { get; set; }
    }
}
