//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfilesDimensions
    {
        public int IdProfileDimension { get; set; }
        public Nullable<int> IdProfile { get; set; }
        public Nullable<int> IdDimension { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<bool> SwitchValue { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Dimensions Dimensions { get; set; }
        public virtual Profiles Profiles { get; set; }
    }
}
