//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promos
    {
        public int IdPromo { get; set; }
        public string TagPromo { get; set; }
        public string Name { get; set; }
        public Nullable<int> FreeDays { get; set; }
        public Nullable<int> IdProfileActivePromo { get; set; }
        public Nullable<int> IdProfileInactivePromo { get; set; }
        public Nullable<int> IdProduct { get; set; }
    }
}
