//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promos
    {
        public int IdPromo { get; set; }
        public string TagPromo { get; set; }
        public string Name { get; set; }
        public Nullable<int> FreeDays { get; set; }
        public Nullable<int> IdProfileActivePromo { get; set; }
        public Nullable<int> IdProfileInactivePromo { get; set; }
        public Nullable<int> IdProduct { get; set; }
    }
}
