//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publishers
    {
        public Publishers()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int IdPublisher { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public string TagName { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
