//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriptions
    {
        public Subscriptions()
        {
            this.UsersDimensions = new HashSet<UsersDimensions>();
        }
    
        public int IdSubscription { get; set; }
        public string ExternalCode { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> RenewalDay { get; set; }
        public Nullable<System.DateTime> LastRenewal { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> IdProfile { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public Nullable<int> PromoFreeDays { get; set; }
        public Nullable<System.DateTime> PromoStarted { get; set; }
        public Nullable<System.DateTime> PromoEnd { get; set; }
        public Nullable<bool> PromoActive { get; set; }
        public Nullable<int> IdPromo { get; set; }
    
        public virtual Profiles Profiles { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<UsersDimensions> UsersDimensions { get; set; }
    }
}
