//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDimensions
    {
        public int IdUserDimension { get; set; }
        public Nullable<int> IdDimension { get; set; }
        public Nullable<decimal> CurrentValue { get; set; }
        public Nullable<System.DateTime> DateLastUpdate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> IdSubscription { get; set; }
        public Nullable<bool> SwitchValue { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Dimensions Dimensions { get; set; }
        public virtual Subscriptions Subscriptions { get; set; }
    }
}
