//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDimensions
    {
        public int IdUserDimension { get; set; }
        public Nullable<int> IdDimension { get; set; }
        public Nullable<decimal> CurrentValue { get; set; }
        public Nullable<System.DateTime> DateLastUpdate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> IdSubscription { get; set; }
        public Nullable<bool> SwitchValue { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Dimensions Dimensions { get; set; }
        public virtual Subscriptions Subscriptions { get; set; }
    }
}
