//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Subscriptions = new HashSet<Subscriptions>();
        }
    
        public int IdUser { get; set; }
        public string ExternalCode { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual ICollection<Subscriptions> Subscriptions { get; set; }
    }
}
