//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Subscriptions = new HashSet<Subscriptions>();
        }
    
        public int IdUser { get; set; }
        public string ExternalCode { get; set; }
        public Nullable<int> IdProduct { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual ICollection<Subscriptions> Subscriptions { get; set; }
    }
}
